openapi: "3.0.0"

info:
  title: "Open DevOps MSG Center"
  version: "1.0.0"

servers:
  - url: http://0.0.0.0/

tags:
  - name: "WeChat"
  - name: "FeiShu"
  - name: "Gitlab"
  - name: "Harbor"

paths:
  /healthy:
    get:
      description: Healthy
      operationId: api.apiHealthy.healthy
      responses:
        200:
          description: Healthy

  /gitlab/invoke:
    post:
      tags:
        - "Gitlab"
      description: GitLab Webhook Invoke
      operationId: api.apiGitlab.invoke
      responses:
        200:
          description: Invoke Succeed

  /harbor/invoke:
    post:
      tags:
        - "Harbor"
      description: Harbor Webhook Invoke
      operationId: api.apiHarbor.invoke
      responses:
        200:
          description: Invoke Succeed
